name: buddydude.dev
description: "Devon Ducharme's official website."
url: https://buddydude.dev
author: Devon Ducharme
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
defaults:
  scope:
    path: ""